/** Presentation labels only: persisted identifiers and user content remain unchanged. */
const labels: Record<string, string> = {
  row: "Hàng",
  frames: "Số khung hình",
  frameDurationMs: "Thời lượng khung hình (ms)",
  speakerName: "Tên người nói",
  avatarAssetId: "Mã ảnh đại diện",
  choices: "Các lựa chọn",
  tile: "Ô bản đồ",
  scenes: "Các cảnh",
  objects: "Các đối tượng",
  components: "Các thành phần",
  properties: "Thuộc tính",
  layers: "Các lớp",
  settings: "Cài đặt",
  name: "Tên",
  id: "Mã",
  Transform: "Biến đổi",
  SpriteRenderer: "Hiển thị hình ảnh",
  Collider: "Vùng va chạm",
  Animator: "Hoạt ảnh",
  Movement: "Di chuyển",
  Health: "Sức khỏe",
  Dialogue: "Hội thoại",
  Interactable: "Tương tác",
  InventoryItem: "Vật phẩm",
  Trigger: "Kích hoạt",
  AudioSource: "Nguồn âm thanh",
  Quest: "Nhiệm vụ",
  Script: "Mã kịch bản",
  Text: "Văn bản",
  UIImage: "Ảnh giao diện",
  UIButton: "Nút giao diện",
  UIPanel: "Bảng giao diện",
  Camera: "Máy quay",
  Tilemap: "Bản đồ ô",
  SpawnPoint: "Điểm xuất hiện",
  MiniGame: "Trò chơi nhỏ",
  Custom: "Tùy chỉnh",
  TRIGGER: "Vùng kích hoạt",
  DECORATION: "Trang trí",
  TILEMAP: "Bản đồ ô",
  CUSTOM: "Tùy chỉnh",
  WORLD: "Thế giới",
  UI: "Giao diện",
  COLLISION: "Va chạm",
  MIXED: "Hỗn hợp",
  MAP: "Bản đồ",
  STORY: "Cốt truyện", MINI_GAME: "Trò chơi nhỏ",
  MENU: "Trình đơn",
  GROUP: "Nhóm",
  SPRITE: "Hình ảnh",
  CHARACTER: "Nhân vật",
  NPC: "Nhân vật phụ",
  ITEM: "Vật phẩm",
  MAP_TILESET: "Bộ ô bản đồ",
  AUDIO: "Âm thanh",
  EFFECT: "Hiệu ứng",
  IMAGE: "Hình ảnh",
  USER: "Người dùng",
  FONT: "Phông chữ",
  OTHER: "Khác",
  OBJECT: "Đối tượng",
  RECTANGLE: "Hình chữ nhật",
  CIRCLE: "Hình tròn",
  PLAYER: "Người chơi",
  AI: "Tự động",
  NONE: "Không có",
  UP: "Lên",
  DOWN: "Xuống",
  LEFT: "Trái",
  RIGHT: "Phải",
  CENTER: "Giữa",
  SINGLE: "Đơn lẻ",
  STACK: "Xếp chồng",
  ENTER: "Đi vào",
  EXIT: "Đi ra",
  INTERACT: "Tương tác",
  CLICK: "Nhấp chuột",
  GLOBAL: "Toàn cục",
  SCENE: "Cảnh",
  READY: "Sẵn sàng",
  TOMBSTONED: "Đã xóa",
  x: "X",
  y: "Y",
  width: "Chiều rộng",
  height: "Chiều cao",
  rotation: "Góc xoay",
  scaleX: "Tỉ lệ X",
  scaleY: "Tỉ lệ Y",
  pivot: "Tâm xoay",
  assetId: "Mã tài nguyên",
  frame: "Khung hình",
  visible: "Hiển thị",
  opacity: "Độ đậm",
  flipX: "Lật ngang",
  flipY: "Lật dọc",
  shape: "Hình dạng",
  radius: "Bán kính",
  offsetX: "Độ lệch X",
  offsetY: "Độ lệch Y",
  isTrigger: "Là vùng kích hoạt",
  collisionLayerId: "Mã lớp va chạm",
  frameWidth: "Chiều rộng khung hình",
  frameHeight: "Chiều cao khung hình",
  initialState: "Trạng thái ban đầu",
  states: "Các trạng thái",
  speed: "Tốc độ",
  controls: "Điều khiển",
  initialDirection: "Hướng ban đầu",
  current: "Hiện tại",
  maximum: "Tối đa",
  startNodeId: "Mã nút bắt đầu",
  nodes: "Các nút hội thoại",
  range: "Phạm vi",
  prompt: "Lời nhắc",
  enabled: "Bật",
  eventId: "Mã sự kiện",
  itemKey: "Khóa vật phẩm",
  displayName: "Tên hiển thị",
  description: "Mô tả",
  iconAssetId: "Mã ảnh biểu tượng",
  collectible: "Có thể thu thập",
  quantityMode: "Chế độ số lượng",
  maximumQuantity: "Số lượng tối đa",
  appearanceConditionId: "Mã điều kiện xuất hiện",
  triggerEventId: "Mã sự kiện kích hoạt",
  activation: "Cách kích hoạt",
  once: "Chỉ một lần",
  cooldownMs: "Thời gian chờ (ms)",
  conditionId: "Mã điều kiện",
  eventIds: "Các mã sự kiện",
  volume: "Âm lượng",
  loop: "Lặp lại",
  autoplay: "Tự động phát",
  fadeInMs: "Thời gian tăng âm (ms)",
  fadeOutMs: "Thời gian giảm âm (ms)",
  questKey: "Khóa nhiệm vụ",
  scriptIds: "Các mã kịch bản",
  anchorX: "Điểm neo X",
  anchorY: "Điểm neo Y",
  visibilityVariable: "Biến hiển thị",
  text: "Nội dung",
  fontAssetId: "Mã phông chữ",
  fontSize: "Cỡ chữ",
  color: "Màu sắc",
  align: "Căn chỉnh",
  actionEventId: "Mã sự kiện hành động",
  label: "Nhãn",
  backgroundColor: "Màu nền",
  borderColor: "Màu viền",
  followObjectId: "Mã đối tượng theo dõi",
  bounds: "Giới hạn",
  smoothing: "Độ mượt",
  tilesetAssetId: "Mã bộ ô bản đồ",
  tileWidth: "Chiều rộng ô",
  tileHeight: "Chiều cao ô",
  columns: "Số cột",
  rows: "Số hàng",
  tiles: "Các ô",
  tag: "Thẻ",
  initial: "Điểm bắt đầu",
  moduleId: "Mã mô-đun",
  returnSceneId: "Mã cảnh quay về",
  resultEventId: "Mã sự kiện kết quả",
  definitionKey: "Khóa định nghĩa",
  config: "Cấu hình",
  scope: "Phạm vi",
  sceneId: "Mã cảnh",
  variableId: "Mã biến",
};
export function studioLabel(value: string): string {
  return labels[value] ?? value;
}
export function studioFieldLabel(path: string): string {
  return path.split(".").map(studioLabel).join(" · ");
}

/** Keep local Vietnamese guidance; remote diagnostics receive a localized fallback. */
export function studioErrorMessage(error: unknown, fallback: string): string {
  return error instanceof Error && /[À-ỹ]/u.test(error.message)
    ? error.message
    : fallback;
}
