import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, test, vi } from "vitest";
import { AdminUsers } from "../components/admin-management/admin-users";
import { AdminGames } from "../components/admin-management/admin-games";
import { api, ApiError } from "../lib/api-client";
vi.mock("next/navigation", () => ({ usePathname: () => "/admin/users" }));
vi.mock("../lib/api-client", async (original) => ({ ...await original<typeof import("../lib/api-client")>(), api: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }));
const user = { id: "u", email: "user@example.test", displayName: "Người thử", role: "USER" as const, isActive: true, version: 1, createdAt: "2026-09-16T00:00:00.000Z", updatedAt: "2026-09-16T00:00:00.000Z", gameCount: 0 };
const game = { id: "g", ownerId: "u", ownerEmail: user.email, ownerName: user.displayName, submittedAt: null, buildCount: 0, releaseCount: 0, title: "Game thử", slug: "game-thu", description: "", accessMode: "GUEST_ALLOWED" as const, visibility: "DRAFT" as const, moderationState: "CLEAR" as const, reviewState: "DRAFT" as const, sourceType: "CODE" as const, artifactReady: false, artifactVersion: 0, createdAt: user.createdAt, updatedAt: user.updatedAt };
beforeEach(() => { vi.resetAllMocks(); vi.mocked(api.get).mockImplementation(async (path) => path.includes("/users/") ? user : path.includes("/games/") ? game : { items: [], total: 0 }); });
test("users filter and paginate ten results", async () => {
 render(<AdminUsers initialUsers={{ items: [user], total: 11 }} currentUserId="admin" />);
 fireEvent.click(screen.getByRole("button", { name: "Trang sau" }));
 await waitFor(() => expect(api.get).toHaveBeenCalledWith(expect.stringContaining("offset=10&limit=10")));
 fireEvent.change(screen.getByLabelText("Vai trò lọc"), { target: { value: "ADMIN" } });
 fireEvent.click(screen.getByRole("button", { name: "Áp dụng bộ lọc" }));
 await waitFor(() => expect(api.get).toHaveBeenCalledWith(expect.stringContaining("role=ADMIN")));
});
test("user save conflicts preserve draft and hide raw API messages", async () => {
 render(<AdminUsers initialUsers={{ items: [user], total: 1 }} currentUserId="admin" />);
 fireEvent.click(screen.getByRole("button", { name: /Sửa user@example/ }));
 await screen.findByLabelText("Email");
 fireEvent.change(screen.getByLabelText("Tên hiển thị"), { target: { value: "Bản thảo" } });
 vi.mocked(api.patch).mockRejectedValue(new ApiError(409, "sensitive SQL"));
 fireEvent.click(screen.getByRole("button", { name: "Lưu người dùng" }));
 expect(await screen.findByRole("alert")).toHaveTextContent("Bản thảo của bạn vẫn được giữ");
 expect(screen.getByLabelText("Tên hiển thị")).toHaveValue("Bản thảo");
 expect(screen.queryByText(/sensitive SQL/)).not.toBeInTheDocument();
 vi.spyOn(window, "confirm").mockReturnValue(false);
 fireEvent.click(screen.getByRole("button", { name: "Hủy chỉnh sửa" }));
 expect(screen.getByLabelText("Tên hiển thị")).toHaveValue("Bản thảo");
});
test("game delete requires confirmation and carries optimistic timestamp", async () => {
 render(<AdminGames initialGames={{ items: [game], total: 1 }} />);
 fireEvent.click(screen.getByRole("button", { name: "Sửa Game thử" }));
 await screen.findByLabelText("Tiêu đề");
 vi.spyOn(window, "confirm").mockReturnValue(false);
 fireEvent.click(screen.getByRole("button", { name: "Xóa game" }));
 expect(api.delete).not.toHaveBeenCalled();
 vi.spyOn(window, "confirm").mockReturnValue(true);
 vi.mocked(api.delete).mockRejectedValue(new ApiError(409, "foreign key"));
 fireEvent.click(screen.getByRole("button", { name: "Xóa game" }));
 expect(await screen.findByRole("alert")).toHaveTextContent("cách ly");
 expect(api.delete).toHaveBeenCalledWith("/admin/games/g", { updatedAt: game.updatedAt });
});
test("create validates passwords and pending create disables submission", async () => {
 render(<AdminUsers initialUsers={{ items: [], total: 0 }} currentUserId="admin" />);
 fireEvent.click(screen.getByRole("button", { name: "Thêm người dùng" }));
 fireEvent.change(screen.getByLabelText("Email"), { target: { value: "new@example.test" } });
 fireEvent.change(screen.getByLabelText("Mật khẩu"), { target: { value: "weakpassword" } });
 fireEvent.click(screen.getByRole("button", { name: "Lưu người dùng" }));
 expect(await screen.findByRole("alert")).toHaveTextContent("mật khẩu");
 expect(api.post).not.toHaveBeenCalled();
 fireEvent.change(screen.getByLabelText("Mật khẩu"), { target: { value: "StrongPass123!" } });
 let reject!: (error: Error) => void;
 vi.mocked(api.post).mockImplementation(() => new Promise((_, fail) => { reject = fail; }));
 fireEvent.click(screen.getByRole("button", { name: "Lưu người dùng" }));
 expect(screen.getByRole("button", { name: "Đang lưu…" })).toBeDisabled();
 reject(new Error("network"));
 expect(await screen.findByRole("alert")).toHaveTextContent("Không thể");
 expect(screen.getByLabelText("Email")).toHaveValue("new@example.test");
});
test("dirty game blocks links, reload, and browser unload when discard is declined", async () => {
 render(<AdminGames initialGames={{ items: [game], total: 1 }} />);
 fireEvent.click(screen.getByRole("button", { name: "Sửa Game thử" }));
 await screen.findByLabelText("Tiêu đề");
 fireEvent.change(screen.getByLabelText("Tiêu đề"), { target: { value: "Bản thảo game" } });
 vi.spyOn(window, "confirm").mockReturnValue(false);
 fireEvent.click(screen.getByRole("button", { name: "Tải lại bản mới nhất" }));
 expect(screen.getByLabelText("Tiêu đề")).toHaveValue("Bản thảo game");
 const click = new MouseEvent("click", { bubbles: true, cancelable: true });
 screen.getByRole("link", { name: "Tổng quan" }).dispatchEvent(click);
 expect(click.defaultPrevented).toBe(true);
 const unload = new Event("beforeunload", { cancelable: true }); window.dispatchEvent(unload);
 expect(unload.defaultPrevented).toBe(true);
});
test("game metadata save carries current timestamp and displays server-reset review state", async () => {
 render(<AdminGames initialGames={{ items: [game], total: 1 }} />);
 vi.mocked(api.get).mockResolvedValueOnce({ ...game, reviewState: "APPROVED", visibility: "PUBLIC" });
 fireEvent.click(screen.getByRole("button", { name: "Sửa Game thử" }));
 await screen.findByLabelText("Tiêu đề");
 fireEvent.change(screen.getByLabelText("Tiêu đề"), { target: { value: "Tên mới" } });
 vi.mocked(api.patch).mockResolvedValue({ ...game, title: "Tên mới", updatedAt: "2026-09-16T01:00:00.000Z" });
 fireEvent.click(screen.getByRole("button", { name: "Lưu game" }));
 await waitFor(() => expect(screen.getByLabelText("Hiển thị")).toHaveValue("DRAFT"));
 expect(api.patch).toHaveBeenCalledWith("/admin/games/g", expect.objectContaining({ title: "Tên mới", updatedAt: game.updatedAt }));
});
